apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  serviceAccountName: jenkinsci
  containers:
#  - name: buildah
#    image: quay.io/buildah/stable
#    command:
#    - cat
#    tty: true
#    securityContext:
#      allowPrivilegeEscalation: true
#      privileged: true
  - name: kaniko
#    image: ppintogbm/kaniko:jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
  - name: ace
    image: ibmcom/ace
    command: 
    - "/bin/bash"
    - "-c"
    args: 
    - cat
    tty: true
    env:
    - name: LICENSE
      value: "accept"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      privileged: false
      capabilities:
        add:
        - SETPCAP
        - AUDIT_WRITE
        - CHOWN
        - NET_RAW
        - DAC_OVERRIDE
        - FOWNER
        - FSETID
        - KILL
        - SETUID
        - SETGID
        - NET_BIND_SERVICE
        - SYS_CHROOT
        - SETFCAP 