apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  volumes:
  - name: docker-credentials
    projected:
      sources:
      - secret: 
          name: ibmcloud-cr
          items:
          - key: .dockerconfigjson
            path: config.json    
  serviceAccountName: jenkinsci
  containers:
  - name: helm
    image: ibmcom/helm:v2.6.0
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.15.0
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-credentials
      mountPath: /kaniko/.docker
  - name: maven
    image: maven:3.6.3-jdk-8
    command: 
    - "/bin/bash"
    - "-c"
    args: 
    - cat
    tty: true
  - name: ace
    image: ibmcom/ace
    command: 
    - "/bin/bash"
    - "-c"
    args: 
    - cat
    tty: true
    env:
    - name: LICENSE
      value: "accept"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      privileged: false
      capabilities:
        add:
        - SETPCAP
        - AUDIT_WRITE
        - CHOWN
        - NET_RAW
        - DAC_OVERRIDE
        - FOWNER
        - FSETID
        - KILL
        - SETUID
        - SETGID
        - NET_BIND_SERVICE
        - SYS_CHROOT
        - SETFCAP 