apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculadora-api.fullname" . }}-api
  labels:
{{ include "calculadora-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "calculadora-api.name" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "calculadora-api.name" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: policies
          configMap:
            name: {{ include "calculadora-api.fullname" . }}-api-policies
        - name: setdbparms
          secret:
            secretName: {{ include "calculadora-api.fullname" . }}-api-setdbparms
      containers:
        - name: {{ .Chart.Name }}-api
          env:
            - name: LICENSE
              value: accept
          volumeMounts:
            - name: policies
              mountPath: /home/aceuser/ace-server/overrides/Policies
            - name: setdbparms
              mountPath: /home/aceuser/initial-config/setdbparms
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            capabilities:
              add:
              - SETPCAP
              - AUDIT_WRITE
              - CHOWN
              - NET_RAW
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETUID
              - SETGID
              - NET_BIND_SERVICE
              - SYS_CHROOT
              - SETFCAP
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
          - containerPort: 7600
            protocol: TCP
            name: admin-http
          - containerPort: 7800
            protocol: TCP
            name: http
          - containerPort: 7843
            protocol: TCP
            name: https
          - containerPort: 9483
            protocol: TCP
            name: 9483-tcp
          livenessProbe: 
            exec:
              command: 
              - chkacehealthy
          readinessProbe: 
            exec:
              command: 
              - chkaceready
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
