apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculadora-api.fullname" . }}-api
  labels:
{{ include "calculadora-api.labels" . | indent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.api.service.type }}
  ports:
    - port: 7800
      protocol: TCP
      name: http
    - port: 7600
      protocol: TCP
      name: admin-http
  selector:
    app.kubernetes.io/name: {{ include "calculadora-api.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
