kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "calculadora-api.fullname" . }}-db-config
  labels:
{{ include "calculadora-api.labels" . | indent 4 }}
data:
  username: {{ required "Usuario para base de datos es requerido!" .Values.db.username }}
  dbname: {{ required "Nombre de base de datos es requerido!" .Values.db.dbname }}